-- FitCheck Engine PostgreSQL Database Schema with pgvector
-- Created: 2026-02-22
-- Purpose: Store research papers with vector embeddings for semantic search

-- Ensure pgvector extension is enabled (run as superuser first)
-- CREATE EXTENSION IF NOT EXISTS vector;

-- Drop table if exists (for clean setup)
DROP TABLE IF EXISTS research_papers;

-- Create the main research_papers table
CREATE TABLE research_papers (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    abstract TEXT,
    text_chunk TEXT NOT NULL,
    embedding vector(384),  -- 384 dimensions for sentence-transformers/all-MiniLM-L6-v2
    metadata JSONB DEFAULT '{}',
    paper_id VARCHAR(255),  -- Original paper identifier from JSONL
    chunk_index INTEGER DEFAULT 0,  -- Which chunk this is for the paper
    chunk_length INTEGER,  -- Length of text chunk in characters
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for optimal performance
CREATE INDEX idx_research_papers_paper_id ON research_papers(paper_id);
CREATE INDEX idx_research_papers_title ON research_papers USING GIN(to_tsvector('english', title));
CREATE INDEX idx_research_papers_text_chunk ON research_papers USING GIN(to_tsvector('english', text_chunk));
CREATE INDEX idx_research_papers_metadata ON research_papers USING GIN(metadata);
CREATE INDEX idx_research_papers_created_at ON research_papers(created_at);

-- pgvector indexes for similarity search
CREATE INDEX idx_research_papers_embedding_cosine ON research_papers USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX idx_research_papers_embedding_l2 ON research_papers USING ivfflat (embedding vector_l2_ops) WITH (lists = 100);

-- Grant permissions to fitcheck_user
GRANT SELECT, INSERT, UPDATE, DELETE ON research_papers TO fitcheck_user;
GRANT USAGE, SELECT ON SEQUENCE research_papers_id_seq TO fitcheck_user;

-- Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for automatic updated_at updates
CREATE TRIGGER update_research_papers_updated_at 
    BEFORE UPDATE ON research_papers 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- View to get database statistics
CREATE OR REPLACE VIEW research_papers_stats AS
SELECT 
    COUNT(*) as total_chunks,
    COUNT(DISTINCT paper_id) as unique_papers,
    AVG(chunk_length) as avg_chunk_length,
    MIN(created_at) as first_ingestion,
    MAX(created_at) as last_ingestion
FROM research_papers;

-- Grant view access
GRANT SELECT ON research_papers_stats TO fitcheck_user;

-- Insert sample data for testing (optional)
-- INSERT INTO research_papers (title, abstract, text_chunk, embedding, metadata, paper_id) 
-- VALUES ('Test Paper', 'Test Abstract', 'Test chunk content', array_fill(0.1, ARRAY[384])::vector, '{"test": true}', 'test_001');

COMMENT ON TABLE research_papers IS 'Stores research paper chunks with vector embeddings for semantic search';
COMMENT ON COLUMN research_papers.embedding IS 'Vector embedding (384-dim) generated by sentence-transformers/all-MiniLM-L6-v2';
COMMENT ON COLUMN research_papers.metadata IS 'Additional paper metadata (authors, journal, year, etc.)';